# Generated by Django 3.2.12 on 2022-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('professional_skill', models.CharField(choices=[('Automation', 'Automation'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational', 'Operational'), ('Other', 'Other')], max_length=22, verbose_name='Professional Skill')),
                ('joined_the_team', models.DateTimeField(auto_now_add=True)),
                ('rank1_tasks_finished', models.IntegerField(default=0)),
                ('rank2_tasks_finished', models.IntegerField(default=0)),
                ('rank3_tasks_finished', models.IntegerField(default=0)),
                ('rank4_tasks_finished', models.IntegerField(default=0)),
                ('tasks_not_finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.TextField(choices=[('Automation', 'Automation'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational', 'Operational'), ('Other', 'Other')], max_length=22, verbose_name='Category')),
                ('rank', models.TextField(choices=[('Rank 1', 'Rank 1'), ('Rank 2', 'Rank 2'), ('Rank 3', 'Rank 3'), ('Rank 4', 'Rank 4')], max_length=6, verbose_name='Rank')),
                ('expiration_time', models.TextField(choices=[('1 Day', '1 Day'), ('3 Day', '3 Day'), ('1 Week', '1 Week'), ('2 Week', '2 Week'), ('1 Month', '1 Month'), ('3 Month', '3 Month'), ('6 Month', '6 Month'), ('a Year', 'a Year')], max_length=7, verbose_name='Expiration Time')),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_proposed', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now=True)),
                ('expire_time_in_hours', models.IntegerField(default=0)),
            ],
        ),
    ]
