# Generated by Django 3.2.12 on 2022-04-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20220414_2324'),
        ('web', '0003_atpmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tagged_profiles',
            field=models.ManyToManyField(to='auth_app.Profile'),
        ),
    ]
