# Generated by Django 3.2.12 on 2022-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_professional_skill'),
        ('web', '0004_task_tagged_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_tasks', models.IntegerField(default=0)),
                ('mechanical_tasks', models.IntegerField(default=0)),
                ('electrical_tasks', models.IntegerField(default=0)),
                ('graphics_and_design_tasks', models.IntegerField(default=0)),
                ('operational_tasks', models.IntegerField(default=0)),
                ('outstanding_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='AtpMessage',
            new_name='WellcomeMessage',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_closed',
            new_name='is_approved_finished',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='is_closed_for_approval',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_occupied',
            new_name='is_suggested',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_proposed',
            new_name='is_taken',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tagged_profiles',
        ),
        migrations.AddField(
            model_name='task',
            name='is_wanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='taken_by',
            field=models.ManyToManyField(blank=True, to='auth_app.Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(choices=[('Automation', 'Automation'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational', 'Operational')], max_length=22, verbose_name='Category'),
        ),
    ]
