# Generated by Django 3.2.12 on 2022-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220416_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WellcomeMessage', models.TextField(default='Optimize The World!')),
                ('automation_engineering_image', models.URLField(default='/static/images/wp3610487.jpg')),
                ('electrical_engineering_image', models.URLField(default='/static/images/eng-2.png')),
                ('mechanical_engineering_image', models.URLField(default='/static/images/546188.jpg')),
                ('graphics_and_design_image', models.URLField(default='/static/images/design-line-graphic-design-graphics-wallpaper-preview.jpg')),
                ('operational_technologist_image', models.URLField(default='/static/images/1880092.jpg')),
            ],
        ),
        migrations.DeleteModel(
            name='WellcomeMessage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rank',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Advanced', 'Advanced')], default=1, max_length=8, verbose_name='Rank'),
            preserve_default=False,
        ),
    ]
