# Generated by Django 3.2.12 on 2022-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220421_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(choices=[('Automation Engineering', 'Automation Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational Technologist', 'Operational Technologist')], max_length=24, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Advanced', 'Advanced')], max_length=8, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='webpagesettings',
            name='automation_engineering_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpagesettings',
            name='electrical_engineering_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpagesettings',
            name='graphics_and_design_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpagesettings',
            name='mechanical_engineering_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpagesettings',
            name='operational_technologist_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
