# Generated by Django 3.2.12 on 2022-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220421_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(choices=[('Automation Engineering', 'Automation Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics and Design', 'Graphics and Design'), ('Operational Technologist', 'Operational Technologist')], max_length=24, verbose_name='Category'),
        ),
    ]
