# Generated by Django 3.2.12 on 2022-04-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_task_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebPageSettings',
            new_name='WebPageSetting',
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expire_time_in_hours',
        ),
    ]
