# Generated by Django 3.2.12 on 2022-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_task_taken_by_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_suggested',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='task',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taken_by_names',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
