# Generated by Django 3.2.12 on 2022-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20220424_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_wanted_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
