# Generated by Django 3.2.12 on 2022-04-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_task_is_wanted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPageSetting',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('date_added', 'title')},
        ),
    ]
