# Generated by Django 3.2.12 on 2022-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220427_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_outstanding',
            field=models.BooleanField(default=False),
        ),
    ]
