# Generated by Django 3.2.12 on 2022-04-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_task_is_outstanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_wanted',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
