# Generated by Django 3.2.12 on 2022-04-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('professional_skill', models.CharField(choices=[('Automation', 'Automation'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational', 'Operational'), ('Other', 'Other')], max_length=22, verbose_name='Professional Skill')),
                ('joined_the_team', models.DateTimeField(auto_now_add=True)),
                ('rank1_tasks_finished', models.IntegerField(default=0)),
                ('rank2_tasks_finished', models.IntegerField(default=0)),
                ('rank3_tasks_finished', models.IntegerField(default=0)),
                ('rank4_tasks_finished', models.IntegerField(default=0)),
                ('tasks_not_finished', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.atpmanageruser')),
            ],
        ),
    ]
