# Generated by Django 3.2.12 on 2022-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20220414_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professional_skill',
            field=models.CharField(choices=[('Automation', 'Automation'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational', 'Operational')], max_length=22, verbose_name='Professional Skill'),
        ),
    ]
