# Generated by Django 3.2.12 on 2022-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_professional_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professional_skill',
            field=models.CharField(choices=[('Automation Engineering', 'Automation Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics & Design', 'Graphics & Design'), ('Operational Technologist', 'Operational Technologist')], max_length=24, verbose_name='Professional Skill'),
        ),
    ]
