# Generated by Django 3.2.12 on 2022-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_professional_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_skill',
            field=models.CharField(choices=[('Automation Engineering', 'Automation Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Graphics and Design', 'Graphics and Design'), ('Operational Technologist', 'Operational Technologist')], max_length=24, verbose_name='Professional Skill'),
        ),
    ]
