# Generated by Django 3.2.12 on 2022-04-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20220421_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('easy_tasks_finished', models.IntegerField(default=0)),
                ('medium_tasks_finished', models.IntegerField(default=0)),
                ('hard_tasks_finished', models.IntegerField(default=0)),
                ('advanced_tasks_finished', models.IntegerField(default=0)),
                ('tasks_not_finished', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.atpmanageruser')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank1_tasks_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank2_tasks_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank3_tasks_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank4_tasks_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tasks_not_finished',
        ),
    ]
