# Generated by Django 3.2.12 on 2022-04-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20220421_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileStats',
            new_name='ProfileStat',
        ),
    ]
