# Generated by Django 3.2.12 on 2022-04-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_rename_profilestats_profilestat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileStat',
        ),
    ]
