# Generated by Django 3.2.12 on 2022-04-28 21:02

import atp_manager.common.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_delete_profilestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atpmanageruser',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[atp_manager.common.validators.validators.validate_only_letters_and_dots_as_separators, django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[atp_manager.common.validators.validators.validate_only_letters_first_is_capital, django.core.validators.MinLengthValidator(2)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[atp_manager.common.validators.validators.validate_only_letters_first_is_capital, django.core.validators.MinLengthValidator(2)], verbose_name='Last name'),
        ),
    ]
